### ISSUE TITLE
Filter client certificates in browser

### ISSUE THREAD

**Issue by parvizrovshanaliyev** [niteshsinghal85/blogs#1]
I have .net core web api, how to Filter client certificates in browser.
When I attempt to visit a website that accepts client certificates, the browser gives me a list of 2 or 3 client certificates

**Comment by niteshsinghal85** [comment]
Hi @parvizrovshanaliyev ,

as far as I know there is no way to configure this in API side. and more over this certificate based authentication is not meant to be used from browser but used mainly in the scenario where you need to call this API from some IoT device or something.

Hope this clarifies your doubt.
